package com.advertising.service.models;


import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldDefaults;

import javax.validation.constraints.NotEmpty;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
@FieldDefaults(level = AccessLevel.PRIVATE)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Dealer {

    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    @Schema(description = "Technical Id generated by the system")
    int id;

    @Schema(description = "The name of dealer")
    @NotEmpty
    String name;

    @Schema(description = "The maximal number of published listings for a dealer", defaultValue = "1")
    @NotEmpty
    int limitOfPublishedListings;

    @Schema(description = "The email address of dealer")
    @NotEmpty
    String email;
}
