package com.advertising.service.models;

import lombok.Data;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldDefaults;

import javax.validation.constraints.NotEmpty;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
@FieldDefaults(level = AccessLevel.PRIVATE)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Listing {

    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    @Schema(description = "Technical Id generated by the system")
    int id;

    @Schema(description = "The name of dealer")
    @NotEmpty
    int dealerId;

    @Schema(description = "The maximal number of published listings for a dealer")
    @NotEmpty
    String vehicle;

    @Schema(description = "The maximal number of published listings for a dealer")
    @NotEmpty
    Long price;

    @Schema(description = "The maximal number of published listings for a dealer", implementation = LocalDateTime.class)
    @NotEmpty
    LocalDateTime createdAt;

    @Schema(description = "The maximal number of published listings for a dealer", implementation = State.class)
    State state;
}
